### PR TITLE
Try to make CI green 🟢 

### PR DESCRIPTION
**Pull request by Leticia-maria**

### CODE REVIEW

**Comment by Leticia-maria** [comment]
```Expected:
    (279.576566152594, 1.0, 1.6280178592103285)
Got:
    (279.576566152594, 1.0, 1.628017859210329)```

**Comment by Leticia-maria** [comment]
I know that using line numbers is not the best way to name commits. Just checking the changes in GitHub Actions logfiles. (The workflow didn't work on forked repositories, that's why I'm updating the commits here).

**Comment by schneiderfelipe** [comment]
> ```
>     (279.576566152594, 1.0, 1.6280178592103285)
> Got:
>     (279.576566152594, 1.0, 1.628017859210329)```
> ```

Numerical errors are not that serious, I normally round the expected value such that they match for the same amount of significant digits.

Besides, those tests are arguably unnecessary, given that we don't yet advertise those algorithms (they're incomplete! 😆). So `# doctest: +SKIP`ping would also be acceptable in this case.

**Comment by Leticia-maria** [comment]
```/home/runner/.cache/pypoetry/virtualenvs/overreact-ykHAvF72-py3.8/lib/python3.8/site-packages/cclib/parser/logfileparser.py:276: DeprecationWarning: inspect.getargspec() is deprecated since Python 3.0, use inspect.signature() or inspect.getfullargspec()
    if len(inspect.getargspec(self.extract)[0]) != 3:```

**Comment by Leticia-maria** [comment]
> > ```
> >     (279.576566152594, 1.0, 1.6280178592103285)
> > Got:
> >     (279.576566152594, 1.0, 1.628017859210329)```
> > ```
> 
> Numerical errors are not that serious, I normally round the expected value such that they match for the same amount of significant digits.
> 
> Besides, those tests are arguably unnecessary, given that we don't yet advertise those algorithms (they're incomplete! laughing). So `# doctest: +SKIP`ping would also be acceptable in this case.

@schneiderfelipe , I know # doctest: +SKIP but this only works if you statically know that some doctest should be skipped. Sometimes it is impossible.

I believe SKIP flag cannot be used for this purpose. I am trying to fix this, because the numerical errors are somewhat random. We won't be able to get away from them.

**Comment by Leticia-maria** [comment]
We can skip the test here: (specifying it, I think it's better than using a flag inside)
```            
- name: Test with pytest
        run: |
             poetry run pytest --cov=. --cov-report=xml
```

I know this is not critical or important, but it is not good to keep the build failing for such a small detail. Don't you agree?

**Comment by schneiderfelipe** [comment]
> I know that using line numbers is not the best way to name commits. Just checking the changes in GitHub Actions logfiles. (The workflow didn't work on forked repositories, that's why I'm updating the commits here).

That's fine, you can always squash/rebase stuff.

**Comment by schneiderfelipe** [comment]
> Check it out:
> 
> ```
> /home/runner/.cache/pypoetry/virtualenvs/overreact-ykHAvF72-py3.8/lib/python3.8/site-packages/cclib/parser/logfileparser.py:276: 
> DeprecationWarning: inspect.getargspec() is deprecated since Python 3.0, use inspect.signature() or inspect.getfullargspec()
> if len(inspect.getargspec(self.extract)[0]) != 3:
> ```

That's OK too (it's on cclib's side, we don't have control over that).

**Comment by schneiderfelipe** [comment]
> > > ```
> > >     (279.576566152594, 1.0, 1.6280178592103285)
> > > Got:
> > >     (279.576566152594, 1.0, 1.628017859210329)```
> > > ```
> > 
> > 
> > Numerical errors are not that serious, I normally round the expected value such that they match for the same amount of significant digits.
> > Besides, those tests are arguably unnecessary, given that we don't yet advertise those algorithms (they're incomplete! laughing). So `# doctest: +SKIP`ping would also be acceptable in this case.
> 
> @schneiderfelipe , I know `# doctest: +SKIP` but this only works if you statically know that some doctest should be skipped. Sometimes it is impossible.

In this case it's fine.

> I believe SKIP flag cannot be used for this purpose. I am trying to fix this, because the numerical errors are somewhat random. We won't be able to get away from them.

That's because the algorithm in question is "stochastic" (it's a quasi-Monte Carlo with Halton sequences). The error should have a nice bound though, so rounding stuff is fine for testing.

**Comment by Leticia-maria** [comment]
You can put this as solved by be98cc7a09841932057047fc9c0eb391d4032a4b, right @schneiderfelipe ?

**Pull request closed without merging**
